# Enable stateless CSRF protection for forms and logins/logouts
framework:
    form:
        csrf_protection:
            token_id: submit

    csrf_protection:
        stateless_token_ids:
            - submit
            - authenticate
            - logout
            - event_close
            - event_stop
            - event_resume
            - request_played
            - request_skipped
            - request_reopen
            - guest_block
            - guest_unblock
