<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Storage for the Doctrine Messenger transports ("async" and "failed").
 *
 * The DSN uses auto_setup=0, so the table must exist before the worker starts.
 * The DDL matches what symfony/doctrine-messenger 7.4 builds itself; workers are
 * woken by pg_notify() from the sender, so no trigger is needed.
 */
final class Version20261001000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create messenger_messages for the Doctrine Messenger transports';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE messenger_messages (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                body TEXT NOT NULL,
                headers TEXT NOT NULL,
                queue_name VARCHAR(190) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750
                ON messenger_messages (queue_name, available_at, delivered_at, id)
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE messenger_messages');
    }
}
